CREATE TABLE admission (
    ksh CHAR(30) PRIMARY KEY,
    zkzh CHAR(30),
    sfzh CHAR(30),
    xm CHAR(100),
    xb CHAR(10),
    lqzt CHAR(30),
    ssmc CHAR(30),
    pcmc VARCHAR(255),
    klmc CHAR(50),
    jhxz CHAR(100),
    tdcj CHAR(10),
    yxmc VARCHAR(255),
    lqzymc VARCHAR(255),
    xymc VARCHAR(255),
    xqmc VARCHAR(255),
    tzsbh CHAR(50),
    emsdh CHAR(50),
    sfyzm CHAR(4),
    jtdz VARCHAR(255),
    yzbm CHAR(10),
    sjr CHAR(50),
    bdsj CHAR(50),
    sjh CHAR(20),
    bz VARCHAR(255),
    cxcs INT DEFAULT 0,
    last_update_time TIMESTAMP,
    import_batch_id CHAR(36),
    import_time TIMESTAMP
);